name: main workflow

on:
  push:
  workflow_dispatch:

jobs:
  quality:
    runs-on: [self-hosted]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      #- name: Setup python 3.7
        #uses: actions/setup-python@v2
        #with:
          #python-version: 3.7

      #- name: Install project dependencies
        #run: make install

      #- name: Run security check
      #un: make check-sec

      - name: Run code quality
        uses: make lint